name: Happy Language CD

on:
  push:
    branches: [ main ]
    paths:
      - '**'
      - '.github/workflows/happy-deploy.yaml'
  workflow_dispatch:

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Java 21
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # Build happy.jar automatically
      - name: Build happy.jar
        run: |
          rm -rf build
          mkdir build
          javac -d build $(find . -name "*.java")
          jar cfe happy.jar Happy.HappyMain -C build .

      # Run Happy REPL tests
      - name: Run REPL tests
        run: |
          java -cp build Happy.ReplTestRunner

      # Azure Login (using azure's OIDC setup)
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.HAPPYLANGUAGE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.HAPPYLANGUAGE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.HAPPYLANGUAGE_AZURE_SUBSCRIPTION_ID }}

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.HAPPYLANGUAGE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.HAPPYLANGUAGE_REGISTRY_PASSWORD }}
          containerAppName: happy-language
          resourceGroup: DefaultResourceGroup-EUS
          imageToBuild: parispig/happy-language:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
